# Generated by Django 5.2 on 2025-04-26 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(default='user.png', upload_to='')),
                ('cover_image', models.ImageField(default='cover.png', upload_to='')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.ManyToManyField(blank=True, related_name='followed', to='profiles.profile')),
            ],
        ),
    ]
