# Generated by Django 5.1.7 on 2025-04-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_avatar.jpg', null=True, upload_to='media/profile_pics'),
        ),
    ]
