# Generated by Django 5.2 on 2025-04-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_picture_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_profile_400x400.png', upload_to='media/profile_pics'),
        ),
    ]
