# Generated by Django 5.2 on 2025-05-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/defualt/user.png', upload_to='media/profile_pics'),
        ),
    ]
