# Generated by Django 5.2 on 2025-04-27 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='retweets',
            old_name='retweeted',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='retweets',
            unique_together={('user', 'tweet')},
        ),
    ]
