# Generated by Django 5.2 on 2025-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_tweet_parent_alter_comment_tweet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(max_length=280),
        ),
        migrations.AddField(
            model_name="comment",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="tweets.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="tweets.hashtag"
            ),
        ),
    ]
