# Generated by Django 5.2 on 2025-04-29 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0006_tweet_views_tweetshare_bookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweetshare",
            old_name="created_at",
            new_name="shared_at",
        ),
        migrations.AddField(
            model_name="tweet",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_tweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="shared_by_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="tweets_shared_directly",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="views",
        ),
        migrations.AlterField(
            model_name="tweetshare",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_logs",
                to="tweets.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweetshare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_tweets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
