# Generated by Django 5.2 on 2025-04-30 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_rename_created_at_tweetshare_shared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
