# Generated by Django 5.2 on 2025-05-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_remove_tweet_image_alter_tweet_user_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
