# Generated by Django 5.2 on 2025-05-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_alter_tweet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='bookmarks',
        ),
    ]
